- name: Ansible jobs create
  hosts: localhost
  become: yes
  vars:
    jenkins_url: http://172.31.47.107:8080
    jenkins_user: admin
    jenkins_password: {{ lookup('amazon.aws.aws_ssm','jenkins_password', region='us-east-1' ) }}
  tasks:
    - name: Create a jenkins job - frontend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: frontend
        password: admin123
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"

    - name: Create a jenkins job - backend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: backend
        password: admin123
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"

    - name: Create a jenkins job - Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-terraform
        password: admin123
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"

    - name: Create a jenkins job - Expense Parameter
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-parameter
        password: admin123
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"




