- name: Ansible jobs create
  hosts: localhost
  become: yes
  vars:
    jenkins_url: http://172.31.47.107:8080
    jenkins_user: admin
    jenkins_password: "{{ lookup('amazon.aws.aws_ssm','jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: Create a jenkins job - frontend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: frontend
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"
      vars:
        repo_name: expense-frontend
        auto_trigger: true

    - name: Create a jenkins job - backend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: backend
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"
      vars:
        repo_name: expense-backend
        auto_trigger: true

    - name: Create a jenkins job - Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-terraform
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"
      vars:
        repo_name: expense-terraform
        auto_trigger: false

    - name: Create a jenkins job - Expense Parameter
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-parameter
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_user }}"
      vars:
        repo_name: parameter-store
        auto_trigger: false




