- name: Ansible jobs create
  hosts: localhost
  become: yes
  tasks:
    - name: Create a jenkins job
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: test
        password: admin123
        url: http://172.31.47.107:8080
        user: admin



